JOPLIN_WEBCLIPPER = 41184
TOKEN = ''
FOLDER = 'Kimchi!'
PYPANDOC_MARKDOWN = 'markdown_github'
FILTER = ''
ANKI_URL = 'http://localhost:8765/'
ANKI_MODEL = 'Korean (foxmask)'  # fields are front/back/romanisation
ANKI_FIELD_COUNT = 3   # number of columns to grab from a joplin table
ANKI_FIELDS = ['Coréen', 'Romanisation', 'Français']
ONE_DECK_PER_NOTE = False    # will create one deck
